PreCommit:
 RuboCop:
   enabled: true
   on_warn: fail
   problem_on_unmodified_line: ignore
   command: ['bundle', 'exec', 'standardrb']
 Standard:
   enabled: true
   on_warn: fail
   problem_on_unmodified_line: ignore

 TrailingWhitespace:
   enabled: true
   problem_on_unmodified_line: ignore
